-- MySQL Script generated by MySQL Workbench
-- mar 31 ene 2017 09:31:02 PET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema diana
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema diana
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diana` DEFAULT CHARACTER SET utf8 ;
USE `diana` ;

-- -----------------------------------------------------
-- Table `diana`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diana`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(64) NOT NULL,
  `Clave` VARCHAR(128) NOT NULL,
  `Estado` ENUM('Activo','Inactivo') NOT NULL DEFAULT 'Activo',
  `Paterno` VARCHAR(128) NOT NULL,
  `Materno` VARCHAR(128) NULL,
  `Nombres` VARCHAR(128) NOT NULL,
  `DNI` VARCHAR(12) NOT NULL,
  `FotoPerfil` VARCHAR(128) NOT NULL DEFAULT 'default.png',
  `email` VARCHAR(512) NULL,
  `movil` VARCHAR(52) NULL,
  `CreditoSMS` INT NOT NULL DEFAULT 10,
  `CreditoMail` INT NOT NULL DEFAULT 10,
  `Registrador` INT NULL,
  `code` VARCHAR(128) NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `Usuario_UNIQUE` (`Usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diana`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diana`.`Departamento` (
  `idDepartamento` INT NOT NULL AUTO_INCREMENT,
  `NombreDepartamento` VARCHAR(128) NOT NULL,
  `UbiGeo` INT(2) NOT NULL,
  PRIMARY KEY (`idDepartamento`),
  FULLTEXT INDEX `NombreDepartamento` (`NombreDepartamento` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `diana`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diana`.`Provincia` (
  `idProvincia` INT NOT NULL AUTO_INCREMENT,
  `NombreProvincia` VARCHAR(128) NOT NULL,
  `UbiGeo` INT(2) NOT NULL,
  `idDepartamento` INT NOT NULL,
  PRIMARY KEY (`idProvincia`),
  FULLTEXT INDEX `NombreProvincia` (`NombreProvincia` ASC),
  INDEX `fk_Provincia_Departamento1_idx` (`idDepartamento` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `diana`.`Distrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diana`.`Distrito` (
  `idDistrito` INT NOT NULL AUTO_INCREMENT,
  `NombreDistrito` VARCHAR(128) NOT NULL,
  `UbiGeo` INT(2) NOT NULL,
  `idProvincia` INT NOT NULL,
  PRIMARY KEY (`idDistrito`),
  FULLTEXT INDEX `NombreDistrito` (`NombreDistrito` ASC),
  INDEX `fk_Distrito_Provincia1_idx` (`idProvincia` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `diana`.`Suscrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diana`.`Suscrito` (
  `idSuscrito` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(156) NULL,
  `Nombre` VARCHAR(156) NULL,
  `Celular` VARCHAR(16) NULL,
  `IMEI` VARCHAR(64) NULL,
  `idUsuario` INT NOT NULL,
  `FechaRegistro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idSuscrito`, `idUsuario`),
  INDEX `fk_Suscrito_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Suscrito_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `diana`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diana`.`PlantillaSMS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diana`.`PlantillaSMS` (
  `idPlantillaSMS` INT NOT NULL AUTO_INCREMENT,
  `Mensaje` VARCHAR(300) NOT NULL,
  `Nombre` VARCHAR(64) NOT NULL,
  `idUsuario` INT NULL,
  PRIMARY KEY (`idPlantillaSMS`),
  INDEX `fk_PlantillaSMS_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_PlantillaSMS_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `diana`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diana`.`Page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diana`.`Page` (
  `idPage` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(128) NOT NULL,
  `Link` TEXT NOT NULL,
  `Tipo` ENUM('Local', 'Externo') NOT NULL DEFAULT 'Externo',
  PRIMARY KEY (`idPage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diana`.`SMS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diana`.`SMS` (
  `idSMS` INT NOT NULL AUTO_INCREMENT,
  `Link` TEXT NULL,
  `idSuscrito` INT NOT NULL,
  `idPlantillaSMS` INT NOT NULL,
  `idPage` INT NOT NULL,
  `FechaRegistro` TIMESTAMP NULL DEFAULT current_timestamp,
  PRIMARY KEY (`idSMS`, `idSuscrito`, `idPlantillaSMS`, `idPage`),
  INDEX `fk_SMS_Suscrito1_idx` (`idSuscrito` ASC),
  INDEX `fk_SMS_PlantillaSMS1_idx` (`idPlantillaSMS` ASC),
  INDEX `fk_SMS_Page1_idx` (`idPage` ASC),
  CONSTRAINT `fk_SMS_Suscrito1`
    FOREIGN KEY (`idSuscrito`)
    REFERENCES `diana`.`Suscrito` (`idSuscrito`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_SMS_PlantillaSMS1`
    FOREIGN KEY (`idPlantillaSMS`)
    REFERENCES `diana`.`PlantillaSMS` (`idPlantillaSMS`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_SMS_Page1`
    FOREIGN KEY (`idPage`)
    REFERENCES `diana`.`Page` (`idPage`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diana`.`PlantillaEmail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diana`.`PlantillaEmail` (
  `idPlantillaEmail` INT NOT NULL AUTO_INCREMENT,
  `file` VARCHAR(256) NOT NULL DEFAULT 'default.html',
  `Idioma` ENUM('ES', 'EN', 'PT') NOT NULL DEFAULT 'ES',
  `Parametros` TEXT NULL,
  `Nombre` VARCHAR(64) NOT NULL,
  `idUsuario` INT NULL,
  PRIMARY KEY (`idPlantillaEmail`),
  INDEX `fk_PlantillaEmail_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_PlantillaEmail_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `diana`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diana`.`Mail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diana`.`Mail` (
  `idMail` INT NOT NULL AUTO_INCREMENT,
  `View` INT NOT NULL DEFAULT 0,
  `idSuscrito` INT NOT NULL,
  `data` TEXT NULL,
  `idPlantillaEmail` INT NOT NULL,
  `idPage` INT NOT NULL,
  `FechaRegistro` TIMESTAMP NULL DEFAULT current_timestamp,
  PRIMARY KEY (`idMail`, `idSuscrito`, `idPlantillaEmail`, `idPage`),
  INDEX `fk_Mail_Suscrito1_idx` (`idSuscrito` ASC),
  INDEX `fk_Mail_PlantillaEmail1_idx` (`idPlantillaEmail` ASC),
  INDEX `fk_Mail_Page1_idx` (`idPage` ASC),
  CONSTRAINT `fk_Mail_Suscrito1`
    FOREIGN KEY (`idSuscrito`)
    REFERENCES `diana`.`Suscrito` (`idSuscrito`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Mail_PlantillaEmail1`
    FOREIGN KEY (`idPlantillaEmail`)
    REFERENCES `diana`.`PlantillaEmail` (`idPlantillaEmail`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Mail_Page1`
    FOREIGN KEY (`idPage`)
    REFERENCES `diana`.`Page` (`idPage`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diana`.`KeySMS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diana`.`KeySMS` (
  `idKeySMS` INT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(45) NOT NULL,
  `Clave` VARCHAR(45) NOT NULL,
  `FechaRegistro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idSMS` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idKeySMS`, `idSMS`),
  INDEX `fk_KeySMS_SMS1_idx` (`idSMS` ASC),
  CONSTRAINT `fk_KeySMS_SMS1`
    FOREIGN KEY (`idSMS`)
    REFERENCES `diana`.`SMS` (`idSMS`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diana`.`KeyMail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diana`.`KeyMail` (
  `idKeyMail` INT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(64) NOT NULL,
  `Clave` VARCHAR(128) NOT NULL,
  `FechaRegistro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idMail` INT NOT NULL,
  PRIMARY KEY (`idKeyMail`, `idMail`),
  INDEX `fk_KeyMail_Mail1_idx` (`idMail` ASC),
  CONSTRAINT `fk_KeyMail_Mail1`
    FOREIGN KEY (`idMail`)
    REFERENCES `diana`.`Mail` (`idMail`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diana`.`NormalSMS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diana`.`NormalSMS` (
  `idNormalSMS` INT NOT NULL AUTO_INCREMENT,
  `Mensaje` VARCHAR(45) NULL,
  `Celular` VARCHAR(45) NULL,
  `idUsuario` INT NOT NULL,
  `FechaRegistro` TIMESTAMP NULL DEFAULT current_timestamp,
  PRIMARY KEY (`idNormalSMS`, `idUsuario`),
  INDEX `fk_NormalSMS_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_NormalSMS_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `diana`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diana`.`Notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diana`.`Notificacion` (
  `idNotificacion` INT NOT NULL AUTO_INCREMENT,
  `Mensaje` VARCHAR(45) NOT NULL,
  `icon` VARCHAR(128) NOT NULL,
  `FechaRegistro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `click` TEXT NULL,
  `Visto` ENUM('Si', 'No') NOT NULL DEFAULT 'No',
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idNotificacion`, `idUsuario`),
  INDEX `fk_Notificacion_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Notificacion_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `diana`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diana`.`Mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diana`.`Mensaje` (
  `idMensaje` INT NOT NULL AUTO_INCREMENT,
  `Mensaje` TEXT NOT NULL,
  `FechaRegistro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idMensaje`, `idUsuario`),
  INDEX `fk_Mensaje_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Mensaje_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `diana`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diana`.`DestinoMensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diana`.`DestinoMensaje` (
  `idMensaje` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `Visto` ENUM('Si', 'No') NOT NULL DEFAULT 'No',
  PRIMARY KEY (`idMensaje`, `idUsuario`),
  INDEX `fk_Mensaje_has_Usuario_Usuario1_idx` (`idUsuario` ASC),
  INDEX `fk_Mensaje_has_Usuario_Mensaje1_idx` (`idMensaje` ASC),
  CONSTRAINT `fk_Mensaje_has_Usuario_Mensaje1`
    FOREIGN KEY (`idMensaje`)
    REFERENCES `diana`.`Mensaje` (`idMensaje`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Mensaje_has_Usuario_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `diana`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diana`.`Tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diana`.`Tarea` (
  `idTarea` INT NOT NULL AUTO_INCREMENT,
  `Tarea` VARCHAR(256) NOT NULL,
  `Avance` INT NOT NULL DEFAULT 0,
  `FechaRegistro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idUsuario` INT NOT NULL,
  `click` TEXT NULL,
  PRIMARY KEY (`idTarea`, `idUsuario`),
  INDEX `fk_Tarea_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Tarea_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `diana`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diana`.`KeyFree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diana`.`KeyFree` (
  `idKeyFree` INT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(64) NOT NULL,
  `Clave` VARCHAR(128) NOT NULL,
  `FechaRegistro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idKeyFree`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diana`.`Permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diana`.`Permiso` (
  `idPermiso` INT NOT NULL AUTO_INCREMENT,
  `Codigo` VARCHAR(45) NOT NULL,
  `Modulo` VARCHAR(45) NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPermiso`, `idUsuario`),
  INDEX `fk_Permiso_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Permiso_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `diana`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
